// Copyright (c) 2024–2026 Holley Studio LLC. All rights reserved.
/**
 * Thesmos adapter system — generates AI assistant instruction files
 * from a shared canonical rule registry. All generator functions are pure.
 *
 * Supported targets and their output paths:
 *   gemini  → GEMINI.md
 *   claude  → CLAUDE.md
 *   cursor  → .cursor/rules/thesmos.mdc
 *   copilot → .github/copilot-instructions.md
 *   codex   → .codex/thesmos.md
 *   agents  → AGENTS.md
 */

import { existsSync, mkdirSync, readFileSync, renameSync, unlinkSync, writeFileSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import type { ThesmosConfig, Severity } from './types';
import { injectGeneratedSection } from './output';
import { SEVERITY_EMOJI } from './severity';
import { generateContextCapsule, saveContextCapsule } from './context-capsule.js';
export { THESMOS_RULES } from './rules/registry';

// ── Types ─────────────────────────────────────────────────────────────────────

export type AdapterTarget =
  | 'gemini'
  | 'claude'
  | 'cursor'
  | 'copilot'
  | 'codex'
  | 'agents';

export interface Rule {
  id: string;
  category: string;
  description: string;
  severity: Severity;
  tags: string[];
  example?: string;
}

export interface AdapterManifest {
  target: AdapterTarget;
  outputPath: string;
  generated: boolean;
  /** 'generated' on success; 'failed' when the write itself errored (see error). */
  status: 'generated' | 'failed';
  error?: string;
}

// ── Output paths ──────────────────────────────────────────────────────────────

export const ADAPTER_OUTPUT_PATHS: Record<AdapterTarget, string> = {
  gemini: 'GEMINI.md',
  claude: 'CLAUDE.md',
  cursor: '.cursor/rules/thesmos.mdc',
  copilot: '.github/copilot-instructions.md',
  codex: '.codex/thesmos.md',
  agents: 'AGENTS.md',
};

// ── Filter helpers (pure) ─────────────────────────────────────────────────────

export function getRulesByTag(rules: Rule[], tag: string): Rule[] {
  return rules.filter((r) => r.tags.includes(tag));
}

export function getRulesBySeverity(rules: Rule[], severity: Severity): Rule[] {
  return rules.filter((r) => r.severity === severity);
}

export function getRulesByCategory(rules: Rule[], categories: string[]): Rule[] {
  const set = new Set(categories);
  return rules.filter((r) => set.has(r.category));
}

// ── Per-target generators (pure) ──────────────────────────────────────────────

/**
 * Short per-target framing sentence — the one thing that actually differs
 * between targets (how each tool is expected to use governance). Everything
 * else in the thin body below is identical across all six targets.
 */
const TARGET_FRAMING: Record<AdapterTarget, string> = {
  gemini: 'The following governs code review in this repo.',
  claude: 'The following governs every task in this repo.',
  cursor: 'The following governs all code suggestions in this repo.',
  copilot: 'The following governs completions and reviews in this repo.',
  codex: 'The following governs all generated code in this repo.',
  agents: 'The following governs any agent or tool working in this repo.',
};

/**
 * Thin adapter body — replaces the old per-rule table entirely (Operation
 * Signal Phase 5). The full 1,137-rule catalog, with descriptions and code
 * examples, embedded in EVERY generated file, was the direct cause of
 * 130-165KB always-loaded adapters. The rule engine is deterministic and
 * queryable on demand (`thesmos explain`) — it does not need to be
 * memorized by an LLM on every single turn.
 *
 * Contains only: what Thesmos is responsible for, a short universal
 * constraint list (not a rule table), how governance decisions are made,
 * how to scan/doctor, how to inspect a specific rule, how to discover an
 * agent, and how to explain a denial. Target: comfortably under 8KB total
 * (this body + the target's own short preamble).
 */
function generateThinAdapterBody(config: ThesmosConfig, target: AdapterTarget): string {
  const parts = [
    `_Generated by Thesmos ${config.version} for **${config.project}**. Full rule catalog: \`.thesmos/RULES.md\`._`,
    '',
    TARGET_FRAMING[target],
    '',
    '## What Thesmos is responsible for',
    `Thesmos is a deterministic governance engine — a fixed rule set covering security, auth, database, API, and framework-specific issues, checked the same way on every run. It is a lookup engine, not a document to read end-to-end.`,
    '',
    '## Non-negotiable constraints',
    '- A BLOCKER finding must never ship. Fix it, or get explicit human sign-off before continuing.',
    '- Never bypass, suppress, or silently work around a BLOCKER-severity rule.',
    '- HIGH findings should be resolved before a task is considered done.',
    '- Prefer small, reversible, verified changes over large unreviewed ones.',
    '- Never overwrite content outside the `THESMOS:GENERATED` markers in this file.',
    '',
    '## How governance decisions are made',
    'Every finding carries a rule id, a severity (BLOCKER/HIGH/MEDIUM/LOW/TECH_DEBT), a message, and a suggested fix — deterministic, not a judgment call. `thesmos validate` gates on BLOCKER only.',
    '',
    '## Commands',
    '- `thesmos scan` — analyze the repo, write `.thesmos/report.json`',
    '- `thesmos review [--base=<ref>]` — show findings for changed files',
    '- `thesmos validate [--base=<ref>]` — gate: exits non-zero on any BLOCKER',
    '- `thesmos doctor` — verify the Thesmos installation itself is healthy',
    '',
    '## Inspecting a specific rule',
    '- `thesmos explain <RULE_ID>` — full detail + live violations for one rule',
    '- `thesmos explain search <query>` — find rules by keyword',
    '- `thesmos explain --list` — every rule id/category/severity',
    '- Full catalog with descriptions and examples: `.thesmos/RULES.md`',
    '',
    '## Discovering an agent',
    '- `thesmos agents:list` — specialist agents available in this repo',
    '- `thesmos pantheon:list` — the full Pantheon god-agent roster, if installed',
    '',
    '## Explaining a denial',
    'A blocked action states which rule fired, why, and a suggested fix inline. For more detail on a specific denial, run `thesmos explain <RULE_ID>` or inspect `.thesmos/report.json`.',
  ];
  return parts.join('\n');
}

export function generateGeminiRules(_rules: Rule[], config: ThesmosConfig): string {
  return generateThinAdapterBody(config, 'gemini');
}

export function generateClaudeRules(_rules: Rule[], config: ThesmosConfig): string {
  return generateThinAdapterBody(config, 'claude');
}

export function generateCursorRules(_rules: Rule[], config: ThesmosConfig): string {
  return generateThinAdapterBody(config, 'cursor');
}

export function generateCopilotRules(_rules: Rule[], config: ThesmosConfig): string {
  return generateThinAdapterBody(config, 'copilot');
}

export function generateCodexRules(_rules: Rule[], config: ThesmosConfig): string {
  return generateThinAdapterBody(config, 'codex');
}

export function generateAgentsRules(_rules: Rule[], config: ThesmosConfig): string {
  return generateThinAdapterBody(config, 'agents');
}

// ── Dispatch tables ───────────────────────────────────────────────────────────

const RULE_GENERATORS: Record<
  AdapterTarget,
  (rules: Rule[], config: ThesmosConfig) => string
> = {
  gemini: generateGeminiRules,
  claude: generateClaudeRules,
  cursor: generateCursorRules,
  copilot: generateCopilotRules,
  codex: generateCodexRules,
  agents: generateAgentsRules,
};

const ADAPTER_PREAMBLES: Record<AdapterTarget, (config: ThesmosConfig) => string> = {
  gemini: (c) =>
    `# ${c.project} — Gemini Code Assist\n\n_Add project-specific context above the generated section._`,

  claude: (c) => [
    `# ${c.project} — Claude Code Instructions`,
    '',
    '> This file is a thin adapter over Thesmos. All canonical rules, playbooks, and governance',
    '> live in `.thesmos/`. Do not edit the generated section — run `npm run thesmos:adapters` to refresh it.',
    '',
    '## Before Each Task',
    '',
    '1. Read `.thesmos/context.md` for current stack, established patterns, and active constraints.',
    '2. Read `.thesmos/README.md` for project architecture and current state.',
    '3. Treat `.thesmos/GUARDRAILS.md` as mandatory — these constraints cannot be overridden.',
    '4. Check `.thesmos/report.json` for current repo intelligence (routes, API auth gaps, large files, boundary risks).',
    '5. For code review behavior, follow `.thesmos/governance/CODE_REVIEW.md`.',
    '6. For AI review expectations, follow `.thesmos/governance/REVIEW_AGENT.md`.',
    '7. Before creating pages, components, API routes, refactors, or build fixes, consult `.thesmos/playbooks/`.',
    '',
    '## Behavioral Rules',
    '',
    '8. Never bypass severity rules — BLOCKER findings must be addressed before continuing.',
    '9. Never overwrite content outside `<!-- THESMOS:GENERATED START … -->` / `<!-- THESMOS:GENERATED END … -->` markers.',
    '10. Prefer small, reversible, tested changes.',
    `11. After changes, run the relevant Thesmos command (\`npm run thesmos:scan\`, \`thesmos:review\`, \`thesmos:validate\`, or \`thesmos:doctor\`).`,
    '12. End each task by listing changed files and test results.',
    '',
    '_Add project-specific context above the generated section._',
  ].join('\n'),

  cursor: (c) =>
    `---\ndescription: Thesmos code governance rules for ${c.project}\nalwaysApply: true\n---\n\n_Add project-specific rules above the generated section._`,
  copilot: (c) =>
    `# Copilot Instructions — ${c.project}\n\n_Add project-specific context above the generated section._`,
  codex: (c) =>
    `# ${c.project} — Codex Instructions\n\n_Add project-specific context above the generated section._`,
  agents: (c) =>
    `# AGENTS — ${c.project}\n\n_Add project-specific agent instructions above the generated section._`,
};

// ── Adapter metadata ──────────────────────────────────────────────────────────

/** Metadata embedded inside every generated adapter section. No timestamps. */
export interface AdapterMeta {
  version: string;
  target: AdapterTarget;
  ruleCount: number;
}

/** Minimal catalog context passed to adapter builders — avoids importing catalog.ts. */
export interface AdapterCatalogEntry {
  id: string;
  name: string;
}

export interface AdapterCatalog {
  agents: AdapterCatalogEntry[];
  skills: AdapterCatalogEntry[];
  profile?: string;
}

/**
 * Compact pointer, not a roster. Enumerating every active agent/skill by
 * name inline (the previous behavior) scaled with the size of the catalog
 * itself — on a repo with the full Pantheon installed, this alone was
 * tens of KB, the second-largest driver of oversized adapters after the
 * per-rule table (Operation Signal Phase 5). "How to discover an agent" is
 * a command to run, not a list to memorize.
 */
function formatCatalogContext(catalog: AdapterCatalog): string {
  if (catalog.agents.length === 0 && catalog.skills.length === 0 && !catalog.profile) return '';
  const lines: string[] = ['', '---', '', '## Active Thesmos Context', ''];
  if (catalog.profile) lines.push(`**Profile:** \`${catalog.profile}\``);
  if (catalog.agents.length > 0) lines.push(`**Active agents:** ${catalog.agents.length}`);
  if (catalog.skills.length > 0) lines.push(`**Active skills:** ${catalog.skills.length}`);
  lines.push('', '_Run `thesmos catalog:list` to see them by name, or `thesmos agents:list` to discover invocation details._');
  return lines.join('\n');
}

/**
 * Parse the THESMOS:META comment from an adapter file.
 * Returns null when the comment is absent or malformed.
 */
export function parseAdapterMeta(content: string): AdapterMeta | null {
  const match = content.match(/<!--\s*THESMOS:META\s+(\{[^}]+\})\s*-->/);
  if (!match || !match[1]) return null;
  try {
    return JSON.parse(match[1]) as AdapterMeta;
  } catch {
    return null;
  }
}

/**
 * Returns whether an adapter file's embedded metadata is current.
 * Freshness is checked by ruleCount and version only — no timestamps.
 */
export function isAdapterFresh(
  content: string,
  rules: Rule[],
  config: ThesmosConfig
): { fresh: boolean; reason: string } {
  const meta = parseAdapterMeta(content);
  if (!meta) {
    return { fresh: false, reason: 'no metadata — run thesmos adapters to refresh' };
  }
  if (meta.ruleCount !== rules.length) {
    return {
      fresh: false,
      reason: `rule count mismatch: file has ${meta.ruleCount}, registry has ${rules.length}`,
    };
  }
  if (meta.version !== config.version) {
    return {
      fresh: false,
      reason: `version mismatch: file has ${meta.version}, current is ${config.version}`,
    };
  }
  return { fresh: true, reason: 'up to date' };
}

// ── Public pure merger ────────────────────────────────────────────────────────

/**
 * Merges a freshly generated rules section into an existing adapter document.
 * If the document is empty, uses the target-specific preamble as the base.
 * Idempotent: calling twice with identical input produces identical output.
 *
 * The generated section always begins with a THESMOS:META comment so that
 * isAdapterFresh() can verify the file without re-running the generator.
 */
export function buildAdapterContent(
  target: AdapterTarget,
  existing: string,
  rules: Rule[],
  config: ThesmosConfig,
  catalog?: AdapterCatalog
): string {
  const base =
    existing.trim() === '' ? ADAPTER_PREAMBLES[target](config) : existing;
  const meta: AdapterMeta = { version: config.version, target, ruleCount: rules.length };
  const metaComment = `<!-- THESMOS:META ${JSON.stringify(meta)} -->`;
  const catalogCtx = catalog ? formatCatalogContext(catalog) : '';
  const generated = `${metaComment}\n${RULE_GENERATORS[target](rules, config)}${catalogCtx}`;
  return injectGeneratedSection(base, 'rules', generated);
}

// ── Target detection ──────────────────────────────────────────────────────────

/**
 * Detects which AI-tool integrations already have a footprint in `root`.
 * `claude` and `agents` are always included — Claude Code is the primary
 * surface and AGENTS.md is the cross-tool convention — every other target
 * is included only when its integration directory/file already exists, so
 * `thesmos adapters`/`thesmos init` don't scatter files for tools the repo
 * doesn't use. Shared by both commands so detection can't drift between them.
 */
export function detectAdapterTargets(root: string): AdapterTarget[] {
  const detected: AdapterTarget[] = ['claude', 'agents'];
  if (existsSync(join(root, 'GEMINI.md'))) detected.push('gemini');
  if (existsSync(join(root, '.cursor')) || existsSync(join(root, '.cursorrules'))) detected.push('cursor');
  if (existsSync(join(root, '.github', 'copilot-instructions.md'))) detected.push('copilot');
  if (existsSync(join(root, '.codex'))) detected.push('codex');
  return detected;
}

// ── I/O orchestrator ──────────────────────────────────────────────────────────

/** Write `content` to `absPath` via a temp-file-then-rename swap — never leaves a partially-written file in place. */
function atomicWriteFileSync(absPath: string, content: string): void {
  const dir = dirname(absPath);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const tmpPath = join(dir, `.${basename(absPath)}.tmp-${process.pid}-${Math.random().toString(36).slice(2)}`);
  writeFileSync(tmpPath, content, 'utf8');
  try {
    renameSync(tmpPath, absPath);
  } catch (err) {
    try { unlinkSync(tmpPath); } catch { /* best-effort cleanup of the temp file */ }
    throw err;
  }
}

/**
 * Writes adapter files for the requested targets under `root`.
 * Existing files are updated in-place (generated section only);
 * manually written content outside the markers is preserved.
 * Writes are atomic (temp file + rename) — a failure on one target never
 * leaves that file partially written, and never blocks the other targets.
 */
export function writeAllAdapters(
  root: string,
  rules: Rule[],
  config: ThesmosConfig,
  targets: AdapterTarget[] = [
    'gemini',
    'claude',
    'cursor',
    'copilot',
    'codex',
    'agents',
  ],
  catalog?: AdapterCatalog
): AdapterManifest[] {
  // Auto-generate context snapshot alongside adapters so CLAUDE.md step 1 always has fresh data.
  // Advisory only — a failure here must never block adapter generation — but it is reported
  // rather than swallowed, since a silently-broken snapshot is its own kind of drift.
  try {
    const capsule = generateContextCapsule(root);
    saveContextCapsule(root, capsule);
  } catch (err) {
    process.stderr.write(
      `thesmos adapters: context snapshot generation failed (non-fatal): ${err instanceof Error ? err.message : String(err)}\n`
    );
  }

  return targets.map((target) => {
    const relPath = ADAPTER_OUTPUT_PATHS[target];
    const absPath = join(root, relPath);
    try {
      const existing = existsSync(absPath) ? readFileSync(absPath, 'utf8') : '';
      const content = buildAdapterContent(target, existing, rules, config, catalog);
      atomicWriteFileSync(absPath, content);
      return { target, outputPath: relPath, generated: true, status: 'generated' };
    } catch (err) {
      return {
        target,
        outputPath: relPath,
        generated: false,
        status: 'failed',
        error: err instanceof Error ? err.message : String(err),
      };
    }
  });
}
